# Generated by Django 5.1.4 on 2026-07-26 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=150)),
                ('estilista', models.CharField(choices=[('maria_gonzalez', 'María González'), ('valentina_torres', 'Valentina Torres'), ('laura_ramirez', 'Laura Ramírez')], max_length=30)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('servicio', models.ForeignKey(help_text='Servicio del catálogo seleccionado para esta cita (RF09).', on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'citas',
                'ordering': ['fecha', 'hora'],
            },
        ),
    ]
