# Generated by Django 5.1.4

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Estilista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('especialidad', models.CharField(help_text='Ej. Coloración, Cortes, Uñas, Maquillaje.', max_length=100)),
                ('dias_laborales', models.JSONField(default=list, help_text='Lista de días que trabaja, ej. ["lunes", "martes"].')),
                ('hora_inicio_jornada', models.TimeField(default='08:00')),
                ('hora_fin_jornada', models.TimeField(default='18:00')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estilista',
                'verbose_name_plural': 'Estilistas',
                'db_table': 'estilistas',
                'ordering': ['nombre_completo'],
            },
        ),
    ]
